image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    SRC: "WebApplication1Core"

before_script:
    - "cd $SRC"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
    artifacts:
        paths:
        - /builds/ebsone/ci-test-mr/WebApplication1Core/WebApplication1Core/bin/Debug/netcoreapp2.1/WebApplication1Core.dll
        - /builds/ebsone/ci-test-mr/WebApplication1Core/WebApplication1Core/bin/Debug/netcoreapp2.1/WebApplication1Core.Views.dll
